// MiraiProcure (未来プロキュア) Master Seed & Sandbox State Dataset

import {
  Supplier,
  PurchaseRequest,
  RFQ,
  Quotation,
  PurchaseOrder,
  InventoryItem,
  Invoice,
  RiskSignal,
  AuditLog,
  UserSession
} from '@/types';

export const DEMO_USERS: UserSession[] = [
  { id: 'usr-1', name: 'System Administrator', email: 'admin@miraiprocure.io', role: 'ADMIN', department: 'Executive AI Command' },
  { id: 'usr-2', name: 'Procurement Manager', email: 'manager@miraiprocure.io', role: 'PROCUREMENT_MANAGER', department: 'Global Procurement' },
  { id: 'usr-3', name: 'Procurement Officer', email: 'officer@miraiprocure.io', role: 'PROCUREMENT_OFFICER', department: 'IT Procurement' },
  { id: 'usr-4', name: 'Finance Manager', email: 'finance@miraiprocure.io', role: 'FINANCE_MANAGER', department: 'Corporate Finance' },
  { id: 'usr-5', name: 'Inventory Manager', email: 'inventory@miraiprocure.io', role: 'INVENTORY_MANAGER', department: 'Supply Chain Operations' },
  { id: 'usr-6', name: 'Executive Approver', email: 'approver@miraiprocure.io', role: 'APPROVER', department: 'Executive Approval Board' },
  { id: 'usr-7', name: 'Supplier Partner', email: 'supplier@abctechnologies.com', role: 'SUPPLIER', department: 'Enterprise Sales' },
];

export const DEMO_SUPPLIERS: Supplier[] = [
  {
    id: 'sup-101',
    code: 'SUP-001',
    companyName: 'TechWorld Solutions',
    contactName: 'Robert Sterling',
    email: 'sales@techworld.io',
    phone: '+91 98765 43210',
    location: 'Bengaluru, India',
    industry: 'IT Hardware & Workstations',
    taxId: '29AAACT1234F1Z5',
    certifications: 'ISO 9001:2015, Green Electronic Standard',
    categories: 'Laptops, Enterprise Desktops, Servers',
    paymentTerms: 'Net 30',
    deliveryScore: 82.0,
    qualityScore: 88.0,
    riskScore: 22.0,
    sustainabilityScore: 78.0,
    status: 'ACTIVE',
  },
  {
    id: 'sup-102',
    code: 'SUP-002',
    companyName: 'ABC Technologies',
    contactName: 'Hiroshi Tanaka',
    email: 'enterprise@abctechnologies.com',
    phone: '+81 3 5555 0142',
    location: 'Tokyo, Japan & Mumbai, India',
    industry: 'Enterprise Hardware & Semiconductors',
    taxId: '27AABCA9876E1ZB',
    certifications: 'ISO 9001, ISO 27001, ESG Tier-1 Certified',
    categories: 'Laptops, Cloud Infrastructure, Memory',
    paymentTerms: 'Net 45',
    deliveryScore: 96.0,
    qualityScore: 94.0,
    riskScore: 8.0, // Exceptionally low risk
    sustainabilityScore: 92.0,
    status: 'ACTIVE',
  },
  {
    id: 'sup-103',
    code: 'SUP-003',
    companyName: 'CyberDistributors Ltd',
    contactName: 'Vikram Mehta',
    email: 'deals@cyberdistributors.net',
    phone: '+91 91234 56789',
    location: 'Delhi NCR, India',
    industry: 'Discount Electronics Wholesale',
    taxId: '07AAACC5544B1ZD',
    certifications: 'Basic GST Registered',
    categories: 'Consumer Laptops, Accessories',
    paymentTerms: 'Immediate / 100% Advance',
    deliveryScore: 54.0,
    qualityScore: 71.0,
    riskScore: 78.0, // High risk!
    sustainabilityScore: 45.0,
    status: 'ACTIVE',
  },
  {
    id: 'sup-104',
    code: 'SUP-004',
    companyName: 'Nippon Micro Systems',
    contactName: 'Akira Takahashi',
    email: 'contact@nipponmicro.jp',
    phone: '+81 6 6123 4567',
    location: 'Osaka, Japan',
    industry: 'Precision Microprocessors & Display Panels',
    taxId: 'JP8010001020304',
    certifications: 'ISO 14001, J-ESG Gold',
    categories: 'Monitors, Display Panels, Embedded Chips',
    paymentTerms: 'Net 30',
    deliveryScore: 91.0,
    qualityScore: 96.0,
    riskScore: 12.0,
    sustainabilityScore: 95.0,
    status: 'ACTIVE',
  },
  {
    id: 'sup-105',
    code: 'SUP-005',
    companyName: 'Horizon Logistics & Hardware',
    contactName: 'Elena Rostova',
    email: 'info@horizonlogistics.eu',
    phone: '+49 30 987654',
    location: 'Berlin, Germany',
    industry: 'Global Freight & Server Racks',
    taxId: 'DE998877665',
    certifications: 'CE Compliant, TUV Rheinland',
    categories: 'Server Racks, Data Center Cooling',
    paymentTerms: 'Net 60',
    deliveryScore: 88.0,
    qualityScore: 89.0,
    riskScore: 18.0,
    sustainabilityScore: 86.0,
    status: 'ACTIVE',
  },
  {
    id: 'sup-106',
    code: 'SUP-006',
    companyName: 'Quantum Components India',
    contactName: 'Ananya Deshmukh',
    email: 'sales@quantumcomp.in',
    phone: '+91 99887 76655',
    location: 'Hyderabad, India',
    industry: 'Passives & Circuit Assemblies',
    taxId: '36AAACQ4321F1ZK',
    certifications: 'ISO 9001',
    categories: 'PCBs, Connectors, Power Units',
    paymentTerms: 'Net 30',
    deliveryScore: 85.0,
    qualityScore: 87.0,
    riskScore: 25.0,
    sustainabilityScore: 70.0,
    status: 'ACTIVE',
  },
  {
    id: 'sup-107',
    code: 'SUP-007',
    companyName: 'Vertex Semiconductor Solutions',
    contactName: 'Marcus Vance',
    email: 'mvance@vertexsemi.com',
    phone: '+1 408 555 0199',
    location: 'San Jose, California, USA',
    industry: 'High Performance SOCs & AI Accelerators',
    taxId: 'US94-3829102',
    certifications: 'ISO 27001, NIST SP 800-161',
    categories: 'AI Chips, GPU Modules, High-Speed Memory',
    paymentTerms: 'Net 30',
    deliveryScore: 93.0,
    qualityScore: 98.0,
    riskScore: 10.0,
    sustainabilityScore: 89.0,
    status: 'ACTIVE',
  },
  {
    id: 'sup-108',
    code: 'SUP-008',
    companyName: 'FutureTech Systems Tokyo',
    contactName: 'Yuki Morimoto',
    email: 'global@futuretech.tokyo',
    phone: '+81 3 4455 6677',
    location: 'Tokyo, Japan',
    industry: 'Robotic Procurement Equipment & IoT',
    taxId: 'JP1020304050607',
    certifications: 'ISO 9001, METI Green Certification',
    categories: 'Robotic Scanners, Smart Warehousing Systems',
    paymentTerms: 'Net 30',
    deliveryScore: 95.0,
    qualityScore: 97.0,
    riskScore: 9.0,
    sustainabilityScore: 94.0,
    status: 'ACTIVE',
  },
  {
    id: 'sup-109',
    code: 'SUP-009',
    companyName: 'Zenith Enterprise Devices',
    contactName: 'Kavita Reddy',
    email: 'enterprise@zenithdevices.com',
    phone: '+91 98450 11223',
    location: 'Chennai, India',
    industry: 'Mobile Workstations & Tablets',
    taxId: '33AAACZ7788P1Z8',
    certifications: 'BIS Certified, EnergyStar 8.0',
    categories: 'Tablets, Laptops, Mobile POS',
    paymentTerms: 'Net 30',
    deliveryScore: 80.0,
    qualityScore: 84.0,
    riskScore: 28.0,
    sustainabilityScore: 75.0,
    status: 'ACTIVE',
  },
  {
    id: 'sup-110',
    code: 'SUP-010',
    companyName: 'Omnia Digital Infrastructure',
    contactName: 'Lucas Dubois',
    email: 'contact@omnia-infra.fr',
    phone: '+33 1 42 68 55 00',
    location: 'Paris, France',
    industry: 'Network Switches & Optical Fiber',
    taxId: 'FR12345678901',
    certifications: 'ISO 27001, GDPR Compliant',
    categories: 'Switches, Routers, Fiber Modules',
    paymentTerms: 'Net 45',
    deliveryScore: 92.0,
    qualityScore: 93.0,
    riskScore: 14.0,
    sustainabilityScore: 88.0,
    status: 'ACTIVE',
  },
];

// Market Benchmark for 500 Laptops
export const MARKET_BENCHMARK_LAPTOPS = {
  category: 'Business Laptops (Core i7 / 16GB / 512GB SSD)',
  marketMin: 42000,
  marketMax: 48000,
  marketAverage: 45000,
  currency: 'INR (₹)',
};

export const DEMO_PURCHASE_REQUESTS: PurchaseRequest[] = [
  {
    id: 'pr-1024',
    prNumber: 'PR-2026-1024',
    title: '500 Business Laptops for Q3 Tech Onboarding',
    requesterName: 'Kenji Sato',
    department: 'Engineering & Product Operations',
    category: 'IT Hardware',
    quantity: 500,
    estimatedUnit: 45000,
    totalBudget: 22500000, // ₹2.25 Crores (22,500,000)
    priority: 'URGENT',
    status: 'AI_PROCESSING',
    justification: 'Quarterly expansion requires 500 standardized high-performance business laptops with 15-day SLA delivery.',
    requiredBy: '2026-09-05',
    createdAt: '2026-08-20T10:15:00Z',
  },
  {
    id: 'pr-1025',
    prNumber: 'PR-2026-1025',
    title: '25 Server Rack Mount Units for Tokyo Data Center',
    requesterName: 'Sophia Martinez',
    department: 'Cloud Operations',
    category: 'Data Center Infrastructure',
    quantity: 25,
    estimatedUnit: 180000,
    totalBudget: 4500000,
    priority: 'HIGH',
    status: 'SUBMITTED',
    justification: 'Replacement of end-of-life rack servers in Tokyo hub.',
    requiredBy: '2026-09-20',
    createdAt: '2026-08-19T14:30:00Z',
  },
  {
    id: 'pr-1026',
    prNumber: 'PR-2026-1026',
    title: '150 Ergonomic Workstations & Dual Monitors',
    requesterName: 'David Chen',
    department: 'Corporate Facilities',
    category: 'Office Equipment',
    quantity: 150,
    estimatedUnit: 25000,
    totalBudget: 3750000,
    priority: 'MEDIUM',
    status: 'APPROVED',
    justification: 'Facilities upgrade for Bengaluru Design Studio.',
    requiredBy: '2026-10-01',
    createdAt: '2026-08-18T11:00:00Z',
  },
];

export const DEMO_RFQS: RFQ[] = [
  {
    id: 'rfq-500',
    rfqNumber: 'RFQ-2026-0500',
    title: 'RFQ for 500 High-Performance Business Laptops (15-Day Delivery)',
    category: 'IT Hardware',
    deadline: '2026-08-25',
    targetBudget: 22500000,
    deliveryDays: 15,
    requirements: '500 Units: Intel Core i7 13th Gen, 16GB LPDDR5 RAM, 512GB NVMe SSD, 14-inch FHD Anti-Glare display, 3-year onsite hardware warranty required.',
    status: 'RESPONSES_RECEIVED',
    createdAt: '2026-08-20T10:30:00Z',
    invitedSuppliers: ['SUP-001', 'SUP-002', 'SUP-003'],
  },
  {
    id: 'rfq-501',
    rfqNumber: 'RFQ-2026-0501',
    title: 'RFQ for Data Center High-Speed Optical Switches',
    category: 'Networking Equipment',
    deadline: '2026-09-10',
    targetBudget: 8500000,
    deliveryDays: 30,
    requirements: '100GbE Managed Fiber Switches with Redundant Power Supplies.',
    status: 'PUBLISHED',
    createdAt: '2026-08-15T09:00:00Z',
    invitedSuppliers: ['SUP-006', 'SUP-010'],
  },
];

export const DEMO_QUOTATIONS: Quotation[] = [
  {
    id: 'q-101',
    quoteNumber: 'QTE-2026-8801',
    rfqId: 'rfq-500',
    supplierId: 'sup-101',
    supplierName: 'TechWorld Solutions (Vendor A)',
    unitPrice: 44500,
    quantity: 500,
    shippingCost: 75000,
    taxCost: 4005000, // 18% GST
    discountAmount: 150000,
    totalLandedCost: 26180000, // (44500*500) + 75000 + 4005000 - 150000
    deliveryDays: 20, // Exceeds target 15 days!
    warrantyMonths: 12, // Only 1 year warranty
    paymentTerms: 'Net 30',
    status: 'ANALYZED',
    isAnomaly: false,
    scores: {
      priceScore: 32.5,
      deliveryScore: 12.0, // Penalty for 20 days vs 15 day requirement
      qualityScore: 13.0,
      warrantyScore: 3.3, // Penalty for 1 year warranty
      riskScore: 7.5,
      pastPerformanceScore: 4.0,
      sustainabilityScore: 3.8,
      compositeScore: 76.1,
      rank: 2,
    },
  },
  {
    id: 'q-102',
    quoteNumber: 'QTE-2026-8802',
    rfqId: 'rfq-500',
    supplierId: 'sup-102',
    supplierName: 'ABC Technologies (Vendor B)',
    unitPrice: 45000,
    quantity: 500,
    shippingCost: 0, // Free white-glove corporate shipping
    taxCost: 4050000, // 18% GST
    discountAmount: 300000, // Bulk enterprise discount
    totalLandedCost: 26250000,
    deliveryDays: 10, // Outstanding 10-day express delivery!
    warrantyMonths: 36, // Full 3-year onsite hardware warranty
    paymentTerms: 'Net 45',
    status: 'RECOMMENDED',
    isAnomaly: false,
    scores: {
      priceScore: 31.8,
      deliveryScore: 20.0, // Perfect score for 10 days
      qualityScore: 14.5,
      warrantyScore: 10.0, // Max score for 36 months warranty
      riskScore: 9.5, // Extremely safe supplier (risk score 8.0)
      pastPerformanceScore: 4.8,
      sustainabilityScore: 4.6,
      compositeScore: 95.2, // WINNER!
      rank: 1,
    },
  },
  {
    id: 'q-103',
    quoteNumber: 'QTE-2026-8803',
    rfqId: 'rfq-500',
    supplierId: 'sup-103',
    supplierName: 'CyberDistributors Ltd (Vendor C)',
    unitPrice: 38000, // Unusually low price (19% below benchmark market average)
    quantity: 500,
    shippingCost: 150000,
    taxCost: 3420000,
    discountAmount: 0,
    totalLandedCost: 22570000,
    deliveryDays: 30, // Way too slow (30 days vs 15 days requirement)
    warrantyMonths: 12,
    paymentTerms: '100% Advance Payment Required',
    status: 'ANALYZED',
    isAnomaly: true,
    anomalyReason: 'ALERT: Unit price of ₹38,000 is 19% below market benchmark (₹42,000–₹48,000). Payment terms require 100% upfront advance for high-risk vendor.',
    scores: {
      priceScore: 35.0, // Highest price score
      deliveryScore: 5.0, // Severely penalized for 30-day delivery SLA failure
      qualityScore: 10.5,
      warrantyScore: 3.3,
      riskScore: 2.0, // High risk penalty
      pastPerformanceScore: 2.5,
      sustainabilityScore: 2.0,
      compositeScore: 60.3,
      rank: 3,
    },
  },
];

export const DEMO_PURCHASE_ORDERS: PurchaseOrder[] = [
  {
    id: 'po-9001',
    poNumber: 'PO-2026-9001',
    supplierName: 'ABC Technologies',
    totalAmount: 22500000,
    landedCost: 26250000,
    deliveryDate: '2026-08-30',
    paymentTerms: 'Net 45',
    status: 'APPROVED',
    approvalStatus: 'APPROVED',
    generatedByAI: true,
    createdAt: '2026-08-20T11:00:00Z',
  },
  {
    id: 'po-9002',
    poNumber: 'PO-2026-9002',
    supplierName: 'Nippon Micro Systems',
    totalAmount: 4800000,
    landedCost: 5664000,
    deliveryDate: '2026-09-15',
    paymentTerms: 'Net 30',
    status: 'SENT',
    approvalStatus: 'APPROVED',
    generatedByAI: false,
    createdAt: '2026-08-15T14:00:00Z',
  },
];

export const DEMO_INVENTORY: InventoryItem[] = [
  {
    id: 'inv-1',
    productName: 'MiraiBook Pro 14 (Business Laptop)',
    sku: 'LAP-MBP-14-500',
    category: 'IT Hardware',
    warehouse: 'Bengaluru Central Hub',
    totalQuantity: 42,
    reservedStock: 35,
    availableStock: 7,
    reorderPoint: 50,
    status: 'REORDER_RECOMMENDED',
  },
  {
    id: 'inv-2',
    productName: 'Server Rack Enclosure 42U',
    sku: 'SRV-RCK-42U',
    category: 'Data Center Infrastructure',
    warehouse: 'Tokyo Data Center 1',
    totalQuantity: 18,
    reservedStock: 5,
    availableStock: 13,
    reorderPoint: 10,
    status: 'OPTIMAL',
  },
  {
    id: 'inv-3',
    productName: '100GbE Fiber Optic Switch Transceiver',
    sku: 'OPT-SW-100G',
    category: 'Networking Equipment',
    warehouse: 'Berlin Operations Warehouse',
    totalQuantity: 8,
    reservedStock: 6,
    availableStock: 2,
    reorderPoint: 15,
    status: 'CRITICAL',
  },
];

export const DEMO_INVOICES: Invoice[] = [
  {
    id: 'invc-401',
    invoiceNumber: 'INV-2026-4401',
    poNumber: 'PO-2026-9001',
    supplierName: 'ABC Technologies',
    invoiceAmount: 26250000,
    poAmount: 26250000,
    goodsReceivedQuantity: 500,
    invoicedQuantity: 520, // 3-Way Match Mismatch: Invoiced 520 vs PO/Received 500!
    threeWayMatchStatus: 'MISMATCH_DETECTED',
    discrepancyReason: 'MISMATCH DETECTED: Supplier invoice specifies 520 units (+20 excess units), whereas Purchase Order PO-2026-9001 and Goods Receipt Note confirm only 500 units received.',
    paymentStatus: 'HELD',
    dueDate: '2026-10-05',
  },
];

export const DEMO_RISK_SIGNALS: RiskSignal[] = [
  {
    id: 'risk-1',
    supplierName: 'CyberDistributors Ltd',
    riskType: 'Anomaly',
    severity: 'HIGH',
    score: 78.0,
    title: 'Potential Price Anomaly & Payment Term Alert',
    description: 'Quotation QTE-2026-8803 is priced 19% below market benchmark (₹38,000 vs ₹45,000 avg) and demands 100% advance payment for an unverified entity.',
    aiSignal: 'Mirai Risk Engine detected high probability of phantom supplier or refurbished hardware fulfillment.',
    createdAt: '2026-08-20T10:45:00Z',
  },
  {
    id: 'risk-2',
    supplierName: 'TechWorld Solutions',
    riskType: 'Delivery',
    severity: 'MEDIUM',
    score: 45.0,
    title: 'SLA Exceedance Signal',
    description: 'Promised 20-day fulfillment exceeds mandatory 15-day operational requirement for PR-2026-1024.',
    aiSignal: 'Delivery delay risk score calculated at 38%. Historical delays detected in 2 previous fulfillment cycles.',
    createdAt: '2026-08-20T10:40:00Z',
  },
];

export const DEMO_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-101',
    userName: 'Kenji Sato',
    action: 'CREATE_PURCHASE_REQUEST',
    entity: 'PurchaseRequest',
    entityId: 'PR-2026-1024',
    details: 'Created Purchase Request PR-2026-1024 for 500 Business Laptops (Budget: ₹2,25,00,000).',
    timestamp: '2026-08-20T10:15:00Z',
  },
  {
    id: 'log-102',
    userName: 'Mirai AI Agent',
    action: 'ANALYZE_QUOTATIONS',
    entity: 'Quotation',
    entityId: 'RFQ-2026-0500',
    details: 'Extracted and scored 3 quotations for RFQ-2026-0500. Calculated Total Landed Cost and multi-factor scores. Flagged QTE-2026-8803 anomaly.',
    timestamp: '2026-08-20T10:35:00Z',
    aiActionId: 'aia-5501',
  },
  {
    id: 'log-103',
    userName: 'Mirai AI Agent',
    action: 'RECOMMEND_VENDOR',
    entity: 'VendorScore',
    entityId: 'SUP-002',
    details: 'Recommended ABC Technologies (Vendor B) with composite score of 95.2/100 (10-day SLA, 3-yr warranty, lowest risk).',
    timestamp: '2026-08-20T10:36:00Z',
    aiActionId: 'aia-5502',
  },
  {
    id: 'log-104',
    userName: 'Eleanor Vance (Approver)',
    action: 'APPROVE_PO_DRAFT',
    entity: 'PurchaseOrder',
    entityId: 'PO-2026-9001',
    details: 'Human-in-the-loop approved Purchase Order PO-2026-9001 for ₹2,25,00,000 after reviewing Mirai AI explainable recommendation.',
    timestamp: '2026-08-20T11:00:00Z',
  },
];
