'use client';

import React, { useState } from 'react';
import { Network, Building2, FileCheck2, FileText, BrainCircuit, Award, ShoppingCart, Boxes, Receipt, Landmark, ArrowRight, Sparkles } from 'lucide-react';

interface NodeDetail {
  id: string;
  name: string;
  subtitle: string;
  icon: any;
  status: 'ACTIVE' | 'COMPLETED' | 'RECOMMENDED' | 'ALERT';
  summary: string;
  metadata: Record<string, string>;
  aiInsight: string;
}

export default function DigitalTwinPage() {
  const nodes: NodeDetail[] = [
    {
      id: 'node-supplier',
      name: 'SUPPLIER 360',
      subtitle: 'ABC Technologies & CyberDistributors',
      icon: Building2,
      status: 'ACTIVE',
      summary: 'Tier-1 active supplier directory & document verification.',
      metadata: { 'Suppliers Onboarded': '10 Enterprise Vendors', 'Top Vendor': 'ABC Technologies (Score 95.2/100)' },
      aiInsight: 'AI verified ISO 9001 and ESG certifications for ABC Technologies.',
    },
    {
      id: 'node-rfq',
      name: 'RFQ DISPATCH',
      subtitle: 'RFQ-2026-0500',
      icon: FileCheck2,
      status: 'COMPLETED',
      summary: '500 Business Laptops with 15-day delivery SLA constraint.',
      metadata: { 'Target Price': '₹45,000 / unit', 'Required SLA': '15 Days', 'Budget': '₹2,25,00,000' },
      aiInsight: 'RFQ auto-generated from PR-2026-1024 natural language prompt.',
    },
    {
      id: 'node-quotation',
      name: 'QUOTATION EXTRACTION',
      subtitle: '3 Quotations Received',
      icon: FileText,
      status: 'ACTIVE',
      summary: 'Parsed Vendor A (TechWorld), Vendor B (ABC Tech), Vendor C (CyberDistributors).',
      metadata: { 'Vendor A': '₹44,500 (20d SLA)', 'Vendor B': '₹45,000 (10d SLA)', 'Vendor C': '₹38,000 (30d SLA)' },
      aiInsight: 'Parsed OCR PDF quotes and computed Total Landed Cost (including shipping & GST).',
    },
    {
      id: 'node-ai-analysis',
      name: 'AI ANALYSIS ENGINE',
      subtitle: 'Multi-Factor Scoring & Landed Cost',
      icon: BrainCircuit,
      status: 'RECOMMENDED',
      summary: 'Evaluates Price (35%), Delivery (20%), Quality (15%), Warranty (10%), Risk (10%).',
      metadata: { 'Scoring Model': 'Weighted Composite Model', 'Vendor B Score': '95.2 / 100' },
      aiInsight: 'Vendor B scored highest due to 10-day SLA and 3-year warranty.',
    },
    {
      id: 'node-vendor-decision',
      name: 'VENDOR DECISION',
      subtitle: 'Recommended: Vendor B',
      icon: Award,
      status: 'RECOMMENDED',
      summary: 'ABC Technologies selected based on SLA compliance & low risk score.',
      metadata: { 'Decision': 'ABC Technologies', 'Savings': '₹3,00,000 Bulk Discount' },
      aiInsight: 'Disqualified Vendor C due to 30-day SLA failure and price anomaly flag.',
    },
    {
      id: 'node-po',
      name: 'PURCHASE ORDER',
      subtitle: 'PO-2026-9001 Draft',
      icon: ShoppingCart,
      status: 'ACTIVE',
      summary: 'High-value PO for ₹2,25,00,000 generated by Mirai AI.',
      metadata: { 'PO Number': 'PO-2026-9001', 'Human Approval': 'REQUIRED' },
      aiInsight: 'Human-in-the-loop approval confirmation triggered for PO execution.',
    },
    {
      id: 'node-inventory',
      name: 'PREDICTIVE INVENTORY',
      subtitle: 'Bengaluru Central Hub',
      icon: Boxes,
      status: 'ALERT',
      summary: 'Current stock: 7 units. Reorder point: 50 units.',
      metadata: { 'Stock Out Risk': '11 Days', 'Reorder Qty': '500 Units' },
      aiInsight: 'Stock depletion model triggered PR generation 11 days before stockout.',
    },
    {
      id: 'node-invoice',
      name: 'INVOICE & 3-WAY MATCH',
      subtitle: 'INV-2026-4401',
      icon: Receipt,
      status: 'ALERT',
      summary: 'PO (500) vs Goods Receipt (500) vs Invoice (520).',
      metadata: { 'Match Status': 'MISMATCH DETECTED', 'Excess Units': '+20 Units' },
      aiInsight: 'Payment held automatically until supplier resolves invoice discrepancy.',
    },
    {
      id: 'node-finance',
      name: 'FINANCE & AUDIT',
      subtitle: 'Spend & Ledger',
      icon: Landmark,
      status: 'COMPLETED',
      summary: 'Corporate spend ledger & immutable audit log entry.',
      metadata: { 'Spend Ledger': 'Updated', 'Audit Trail ID': 'log-104' },
      aiInsight: 'Audit trail recorded end-to-end user and AI actions.',
    },
  ];

  const [selectedNode, setSelectedNode] = useState<NodeDetail>(nodes[3]); // AI Analysis node default

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-800 pb-4">
        <div>
          <div className="flex items-center gap-2">
            <span className="text-[10px] font-mono uppercase bg-cyan-950 text-cyan-400 border border-cyan-500/40 px-2 py-0.5 rounded">
              REAL-TIME DIGITAL TWIN
            </span>
            <span className="text-xs text-slate-400 font-mono">Process Graph Visualizer</span>
          </div>
          <h1 className="text-2xl font-extrabold text-slate-100 mt-1">
            Digital Procurement Twin (Autonomous Process Map)
          </h1>
          <p className="text-xs text-slate-400">
            Interactive visual simulation mapping physical intent to financial settlement. Click any node to inspect live state.
          </p>
        </div>
      </div>

      {/* Horizontal Interactive Process Flow Nodes */}
      <div className="bg-slate-900 border border-slate-800 p-6 rounded-2xl overflow-x-auto shadow-2xl">
        <div className="flex items-center gap-3 min-w-[1100px] py-4">
          {nodes.map((node, index) => {
            const Icon = node.icon;
            const isSelected = selectedNode.id === node.id;

            return (
              <React.Fragment key={node.id}>
                {/* Node Card */}
                <button
                  onClick={() => setSelectedNode(node)}
                  className={`flex flex-col items-center p-3.5 rounded-2xl transition-all duration-200 w-36 text-center select-none ${
                    isSelected
                      ? 'bg-cyan-950 border-2 border-cyan-400 shadow-xl shadow-cyan-500/20 scale-105'
                      : node.status === 'RECOMMENDED'
                      ? 'bg-slate-950 border border-cyan-500/40 hover:border-cyan-400'
                      : node.status === 'ALERT'
                      ? 'bg-slate-950 border border-rose-800/60 hover:border-rose-400'
                      : 'bg-slate-950 border border-slate-800 hover:border-slate-700'
                  }`}
                >
                  <div
                    className={`p-3 rounded-xl mb-2 flex items-center justify-center ${
                      isSelected
                        ? 'bg-cyan-400 text-slate-950 font-bold'
                        : node.status === 'RECOMMENDED'
                        ? 'bg-cyan-950 text-cyan-400 border border-cyan-500/30'
                        : node.status === 'ALERT'
                        ? 'bg-rose-950 text-rose-400 border border-rose-800/40'
                        : 'bg-slate-900 text-slate-400'
                    }`}
                  >
                    <Icon className="h-5 w-5" />
                  </div>
                  <span className="text-[10px] font-extrabold font-mono tracking-wider text-slate-200 uppercase line-clamp-1">
                    {node.name}
                  </span>
                  <span className="text-[9px] text-slate-400 line-clamp-1 mt-0.5">
                    {node.subtitle}
                  </span>
                </button>

                {/* Arrow Connector */}
                {index < nodes.length - 1 && (
                  <ArrowRight className="h-4 w-4 text-slate-600 shrink-0" />
                )}
              </React.Fragment>
            );
          })}
        </div>
      </div>

      {/* Selected Node Detailed Inspector */}
      <div className="bg-slate-900 border border-cyan-500/30 p-6 rounded-2xl space-y-4 shadow-xl">
        <div className="flex items-center justify-between border-b border-slate-800 pb-3">
          <div className="flex items-center gap-3">
            <div className="p-2.5 bg-cyan-950 border border-cyan-500/40 rounded-xl text-cyan-400">
              <selectedNode.icon className="h-6 w-6" />
            </div>
            <div>
              <span className="text-[10px] font-mono uppercase text-cyan-400">Digital Twin Inspector</span>
              <h2 className="text-lg font-extrabold text-slate-100">{selectedNode.name}</h2>
            </div>
          </div>
          <span className="text-xs font-mono bg-cyan-950 text-cyan-300 border border-cyan-500/40 px-3 py-1 rounded-lg">
            {selectedNode.subtitle}
          </span>
        </div>

        <div className="grid md:grid-cols-2 gap-6">
          <div className="space-y-3">
            <h3 className="text-xs font-bold text-slate-300 uppercase tracking-wider font-mono">Node Operational Summary</h3>
            <p className="text-xs text-slate-300 leading-relaxed bg-slate-950 p-3.5 rounded-xl border border-slate-800">
              {selectedNode.summary}
            </p>

            <div className="space-y-2">
              <h3 className="text-xs font-bold text-slate-300 uppercase tracking-wider font-mono">Live Metadata</h3>
              <div className="bg-slate-950 p-3 rounded-xl border border-slate-800 space-y-1.5 font-mono text-xs">
                {Object.entries(selectedNode.metadata).map(([k, v]) => (
                  <div key={k} className="flex justify-between border-b border-slate-800/60 pb-1">
                    <span className="text-slate-400">{k}:</span>
                    <span className="font-semibold text-cyan-300">{v}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>

          <div className="space-y-3">
            <h3 className="text-xs font-bold text-slate-300 uppercase tracking-wider font-mono">Mirai AI Insights</h3>
            <div className="p-4 bg-cyan-950/40 border border-cyan-500/30 rounded-xl text-xs space-y-2">
              <div className="flex items-center gap-2 text-cyan-400 font-bold font-mono">
                <Sparkles className="h-4 w-4" />
                <span>Autonomous Agent Telemetry</span>
              </div>
              <p className="text-slate-200 leading-relaxed font-sans">
                {selectedNode.aiInsight}
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
